export { default as Papers } from "./Papers"
export { default as About } from "./About"
export { default as AddPaper } from "./AddPaper"
export { default as Layout } from "./Layout"
export { default as Charts } from "./Charts"